---
version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka1:
    image: confluentinc/cp-kafka:latest
    hostname: kafka1
    container_name: kafka1
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 3
      # KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      # KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_DELETE_TOPIC_ENABLE: 'true'


  postgres:
    image: 'postgres:14'
    hostname: postgres
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgres-password
      - POSTGRES_USER=postgres
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  # kouncil:
  #   image: consdata/kouncil:latest
  #   hostname: kouncil
  #   container_name: kouncil
  #   environment:
  #     - bootstrapServers=kafka1:9092
  #     - kouncil.auth.active-provider="inmemory"
  #   ports:
  #   - 80:8080



  python:
    hostname: python
    container_name: python
    image: 'python:3.10.1'
    # volumes:
    #   - ./app:/app
    # working_dir: /app
    command:
    - /bin/sleep
    - "86400"

